apiVersion: v1
kind: Service
metadata:
  name: api-lb
spec:
  selector:
    app: api-servicej
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.0.2.100
