apiVersion: apps/v1

kind: Deployment

metadata:

  labels:

    app: mysql

  name: mysql-deployment

spec:

  progressDeadlineSeconds: 600

  replicas: 1

  revisionHistoryLimit: 10

  selector:

    matchLabels:

      app: mysql

  strategy:

    rollingUpdate:

      maxSurge: 25%

      maxUnavailable: 25%

    type: RollingUpdate

  template:

    metadata:

      creationTimestamp: null

      labels:

        app: mysql

    spec:

      containers:

        - image: mysql

          imagePullPolicy: IfNotPresent

          name: mysql

          env:

            - name: MYSQL_ROOT_PASSWORD

              value: "Passwort"

          resources: {}

          terminationMessagePath: /dev/termination-log

          terminationMessagePolicy: File

          ports:

            - containerPort: 3306

              name: mysql
